new(core): update tests/project_examples.

diff --git a/.github/workflows/release-uvx.yml b/.github/workflows/release-uvx.yml
--- a/.github/workflows/release-uvx.yml
+++ b/.github/workflows/release-uvx.yml
@@ -2,8 +2,8 @@ name: Release (uvx)
 
 on:
   push:
-    branches:
-      - master # Si attiva quando fai il merge su master
+    tags:
+      - 'v[0-9]+.[0-9]+.[0-9]+' # push di una versione canonica (es. v1.2.3) senza pre-release
 
 permissions:
   contents: write
@@ -12,7 +12,6 @@ permissions:
 
 jobs:
   build-release:
-    if: startsWith(github.ref, 'refs/tags/')
     runs-on: ubuntu-latest
 
     steps:
@@ -20,6 +19,17 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 # Carica tutta la cronologia per poter confrontare i rami
+
+      - name: Check if tag is on master
+        run: |
+          # Usiamo l'hash del commit (GITHUB_SHA) per evitare problemi di nomi di tag simili
+          git fetch origin master
+          if git branch -r --contains ${GITHUB_SHA} | grep -q "origin/master"; then
+            echo "✅ Tag ${{ github.ref }} is on master branch. Proceeding with release."
+          else
+            echo "❌ Tag ${{ github.ref }} is not on master branch. Aborting release."
+            exit 1
+          fi
 
       - name: Set up Python
         uses: actions/setup-python@v5
